version: '3.7'

services:
  payments:
    container_name: payments
    build:
      context: ./services/payments
      dockerfile: Dockerfile
    command: uvicorn main:app --reload
    ports:
      - 8001:8000
    depends_on:
      - zookeeper
      - kafka

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper